apiVersion: v1
kind: Service
metadata:
  name: angular-app
  namespace: namespace-workflow-1694873231548
spec:
  type: LoadBalancer
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80